#!/bin/bash

## tkooda : 2010-05-04 : command chaining with proper DBUS socket

pid="`grep -l '/e[t]c/xdg/xfce4/xinitrc' /proc/[0-9]*/* 2>/dev/null |cut -d'/' -f3`"
[ -n "${pid}" ] || exit 1

dbus="`strings /proc/${pid}/environ |grep '^DBUS_SESSION_BUS_ADDRESS=' |head -n1 |cut -d'=' -f2-`"
[ -n "${dbus}" ] || exit 2

DBUS_SESSION_BUS_ADDRESS="${dbus}" exec "${@}"

