#!/usr/bin/python

## tkooda : 2010-01-12 : list files/dirs from argv sorted by mtime (do not traverse)

import sys
import os

if len(sys.argv) < 2:
    print >>sys.stderr, "usage: %s [files and dirs..]" % os.path.basename( sys.argv[0] )
    sys.exit( 1 )

items = []

for arg in sys.argv[1:]:
    if not os.path.exists( arg ):
        continue
    try:
        items.append( [ os.path.getmtime( arg ), arg ] )
    except:
        print >>sys.stderr, "WARNING: missing:", arg

try:
    reverse = int( os.getenv( "REVERSE" ) )
except:
    reverse = 0

if reverse:
    items.sort(reverse=True)
else:
    items.sort()

for mtime, path in items:
    print path

