#!/usr/bin/python

## tkooda : 2013-10-11 : read vObject (vCard / vCalendar) from files on argv, print details on stdout

# BUGS:
#  - only prints the first attendee


import sys
import vobject
import datetime
import dateutil.tz


def human_readable_seconds( seconds ):
    minutes = seconds / 60
    h = ""
    
    if minutes / 60 / 24:
        h += "%d d " % ( minutes / 60 / 24 )
    
    if ( minutes / 60 ) % 24:
        h += "%dh " % ( ( minutes / 60 ) % 24 )
    
    if minutes % 60:
        h += "%dm " % ( minutes % 60 )
    
    return h


def get_datetime( dt ):
    localtz = dateutil.tz.tzlocal()
    localtzname = localtz.tzname( dt )
    return dt.strftime("%A %m/%d/%Y @ %I:%M %p  %z") + " (%s)" % localtzname


def get_email( obj ):
#    return '"%s" <%s> (RSVP = %s)' % ( obj.params.get( "CN", "" )[0], obj.value, obj.params.get( "RSVP", "?" )[0] )
    return '"%s" <%s>' % ( obj.params.get( "CN", "" )[0], obj.value )



for f in sys.argv[ 1: ]:
    fd = open( f, "rb" )
    s = fd.read()
    fd.close()
    
    for component in vobject.readComponents( s ):
        print "Start:", get_datetime( component.vevent.dtstart.value )
        print "End:  ", get_datetime( component.vevent.dtend.value )
        duration = component.vevent.dtend.value - component.vevent.dtstart.value
        print "Duration:", human_readable_seconds( duration.seconds )
#        print "Created:", get_datetime( component.vevent.created.value )
        print
        
        print "Organizer:", get_email( component.vevent.organizer )
#        print "Attendee:", get_email( component.vevent.attendee ) # don't show only one
        print
#        print "Priority:", component.vevent.priority.value
        print "Summary:", component.vevent.summary.value
        print "Description:", component.vevent.description.value
        print
        
        if component.vevent.rruleset:
            print "Reoccuring:"
            for i in list( component.vevent.rruleset )[ :10 ]:
                print get_datetime( i )
            if len( list( component.vevent.rruleset ) ) > 10:
                print "( plus %d more )" % ( len( list( component.vevent.rruleset ) ) - 10 )
        print
	print
        
        print "[ COMPONENT: ]"
        del component.vevent.x_alt_desc
        component.prettyPrint()
        print
        print
	
        print "[ RAW: ]"
        print s
        print
