#!/usr/bin/python

## tkooda : 2013-10-11 : read vObject (vCard / vCalendar) from files on argv, print details on stdout

# BUGS:
#  - only prints the first attendee


import sys
import vobject
import datetime
import dateutil.tz


def get_datetime( dt ):
    localtz = dateutil.tz.tzlocal()
    localtzname = localtz.tzname( dt )
    return dt.strftime("%A %m/%d/%Y @ %I:%M %p  %z") + " (%s)" % localtzname

def get_email( obj ):
#    return '"%s" <%s> (RSVP = %s)' % ( obj.params.get( "CN", "" )[0], obj.value, obj.params.get( "RSVP", "?" )[0] )
    return '"%s" <%s>' % ( obj.params.get( "CN", "" )[0], obj.value )


for f in sys.argv[ 1: ]:
    fd = open( f, "rb" )
    s = fd.read()
    fd.close()
    
    for component in vobject.readComponents( s ):
        print "Start:  ", get_datetime( component.vevent.dtstart.value )
        print "End:    ", get_datetime( component.vevent.dtend.value )
        duration = component.vevent.dtend.value - component.vevent.dtstart.value
        duration_minutes = duration.seconds / 60
        print "Duration:",
#        if duration_hours == 1:
#            print "%d hour" % duration_hours,
#        elif duration_hours > 1:
#            print "%d hours" % duration_hours,
        if duration_minutes:
            print "%d minutes" % duration_minutes,
        print
#        print "Created:", get_datetime( component.vevent.created.value )
        print
        print "Organizer:", get_email( component.vevent.organizer )
        print "Attendee:", get_email( component.vevent.attendee )
        print
#        print "Priority:", component.vevent.priority.value
        print "Summary:", component.vevent.summary.value
        print
        if component.vevent.rruleset:
            print "Reoccuring:"
            for i in list( component.vevent.rruleset )[ :10 ]:
                print get_datetime( i )
            if len( list( component.vevent.rruleset ) ) > 10:
                print "( plus %d more )" % ( len( list( component.vevent.rruleset ) ) - 10 )
        print
	print
        
        print "[ COMPONENT: ]"
        del component.vevent.x_alt_desc
        component.prettyPrint()
        print
        print
	
        print "[ RAW: ]"
        print s
        print
