#!/usr/bin/perl

# from Mail::DKIM::Verifier man page

use Mail::DKIM::Verifier;

# create a verifier object
my $dkim = Mail::DKIM::Verifier->new();

# read an email from a file handle
$dkim->load(*STDIN);

# or read an email and pass it into the verifier, incrementally
while (<STDIN>)
{   
    # remove local line terminators
    chomp;
    s/\015$//;

    # use SMTP line terminators
    $dkim->PRINT("$_\015\012");
}
$dkim->CLOSE;

# what is the result of the verify?
print "dkim-verify: " . $dkim->result_detail . "\n";

